//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleData.Library.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LorenIpsum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LorenIpsum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleData.Library.resources.LorenIpsum", typeof(LorenIpsum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string LoremKey_1 {
            get {
                return ResourceManager.GetString("LoremKey_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aliquip.
        /// </summary>
        internal static string LoremKey_10 {
            get {
                return ResourceManager.GetString("LoremKey_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kasd.
        /// </summary>
        internal static string LoremKey_100 {
            get {
                return ResourceManager.GetString("LoremKey_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labore.
        /// </summary>
        internal static string LoremKey_101 {
            get {
                return ResourceManager.GetString("LoremKey_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lacinia.
        /// </summary>
        internal static string LoremKey_102 {
            get {
                return ResourceManager.GetString("LoremKey_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lacus.
        /// </summary>
        internal static string LoremKey_103 {
            get {
                return ResourceManager.GetString("LoremKey_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laoreet.
        /// </summary>
        internal static string LoremKey_104 {
            get {
                return ResourceManager.GetString("LoremKey_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lectus.
        /// </summary>
        internal static string LoremKey_105 {
            get {
                return ResourceManager.GetString("LoremKey_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leo.
        /// </summary>
        internal static string LoremKey_106 {
            get {
                return ResourceManager.GetString("LoremKey_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liber.
        /// </summary>
        internal static string LoremKey_107 {
            get {
                return ResourceManager.GetString("LoremKey_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libero.
        /// </summary>
        internal static string LoremKey_108 {
            get {
                return ResourceManager.GetString("LoremKey_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ligul.
        /// </summary>
        internal static string LoremKey_109 {
            get {
                return ResourceManager.GetString("LoremKey_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aliquyam.
        /// </summary>
        internal static string LoremKey_11 {
            get {
                return ResourceManager.GetString("LoremKey_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ligula.
        /// </summary>
        internal static string LoremKey_110 {
            get {
                return ResourceManager.GetString("LoremKey_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lobortis.
        /// </summary>
        internal static string LoremKey_111 {
            get {
                return ResourceManager.GetString("LoremKey_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lorem.
        /// </summary>
        internal static string LoremKey_112 {
            get {
                return ResourceManager.GetString("LoremKey_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to luctus.
        /// </summary>
        internal static string LoremKey_113 {
            get {
                return ResourceManager.GetString("LoremKey_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to luptatum.
        /// </summary>
        internal static string LoremKey_114 {
            get {
                return ResourceManager.GetString("LoremKey_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maecenas.
        /// </summary>
        internal static string LoremKey_115 {
            get {
                return ResourceManager.GetString("LoremKey_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magna.
        /// </summary>
        internal static string LoremKey_116 {
            get {
                return ResourceManager.GetString("LoremKey_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magnis.
        /// </summary>
        internal static string LoremKey_117 {
            get {
                return ResourceManager.GetString("LoremKey_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to malesuada.
        /// </summary>
        internal static string LoremKey_118 {
            get {
                return ResourceManager.GetString("LoremKey_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to massa.
        /// </summary>
        internal static string LoremKey_119 {
            get {
                return ResourceManager.GetString("LoremKey_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amet.
        /// </summary>
        internal static string LoremKey_12 {
            get {
                return ResourceManager.GetString("LoremKey_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mattis.
        /// </summary>
        internal static string LoremKey_120 {
            get {
                return ResourceManager.GetString("LoremKey_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mauris.
        /// </summary>
        internal static string LoremKey_121 {
            get {
                return ResourceManager.GetString("LoremKey_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mazim.
        /// </summary>
        internal static string LoremKey_122 {
            get {
                return ResourceManager.GetString("LoremKey_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metus.
        /// </summary>
        internal static string LoremKey_123 {
            get {
                return ResourceManager.GetString("LoremKey_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        internal static string LoremKey_124 {
            get {
                return ResourceManager.GetString("LoremKey_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minim.
        /// </summary>
        internal static string LoremKey_125 {
            get {
                return ResourceManager.GetString("LoremKey_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to molestie.
        /// </summary>
        internal static string LoremKey_126 {
            get {
                return ResourceManager.GetString("LoremKey_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mollis.
        /// </summary>
        internal static string LoremKey_127 {
            get {
                return ResourceManager.GetString("LoremKey_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to montes.
        /// </summary>
        internal static string LoremKey_128 {
            get {
                return ResourceManager.GetString("LoremKey_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morbi.
        /// </summary>
        internal static string LoremKey_129 {
            get {
                return ResourceManager.GetString("LoremKey_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ante.
        /// </summary>
        internal static string LoremKey_13 {
            get {
                return ResourceManager.GetString("LoremKey_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mus.
        /// </summary>
        internal static string LoremKey_130 {
            get {
                return ResourceManager.GetString("LoremKey_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nam.
        /// </summary>
        internal static string LoremKey_131 {
            get {
                return ResourceManager.GetString("LoremKey_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nascetur.
        /// </summary>
        internal static string LoremKey_132 {
            get {
                return ResourceManager.GetString("LoremKey_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natoque.
        /// </summary>
        internal static string LoremKey_133 {
            get {
                return ResourceManager.GetString("LoremKey_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nec.
        /// </summary>
        internal static string LoremKey_134 {
            get {
                return ResourceManager.GetString("LoremKey_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neque.
        /// </summary>
        internal static string LoremKey_135 {
            get {
                return ResourceManager.GetString("LoremKey_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to netus.
        /// </summary>
        internal static string LoremKey_136 {
            get {
                return ResourceManager.GetString("LoremKey_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nibh.
        /// </summary>
        internal static string LoremKey_137 {
            get {
                return ResourceManager.GetString("LoremKey_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nihil.
        /// </summary>
        internal static string LoremKey_138 {
            get {
                return ResourceManager.GetString("LoremKey_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nisi.
        /// </summary>
        internal static string LoremKey_139 {
            get {
                return ResourceManager.GetString("LoremKey_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arcu.
        /// </summary>
        internal static string LoremKey_14 {
            get {
                return ResourceManager.GetString("LoremKey_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nisl.
        /// </summary>
        internal static string LoremKey_140 {
            get {
                return ResourceManager.GetString("LoremKey_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string LoremKey_141 {
            get {
                return ResourceManager.GetString("LoremKey_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nobis.
        /// </summary>
        internal static string LoremKey_142 {
            get {
                return ResourceManager.GetString("LoremKey_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non.
        /// </summary>
        internal static string LoremKey_143 {
            get {
                return ResourceManager.GetString("LoremKey_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonummy.
        /// </summary>
        internal static string LoremKey_144 {
            get {
                return ResourceManager.GetString("LoremKey_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonumy.
        /// </summary>
        internal static string LoremKey_145 {
            get {
                return ResourceManager.GetString("LoremKey_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nostrud.
        /// </summary>
        internal static string LoremKey_146 {
            get {
                return ResourceManager.GetString("LoremKey_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nulla.
        /// </summary>
        internal static string LoremKey_147 {
            get {
                return ResourceManager.GetString("LoremKey_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nullam.
        /// </summary>
        internal static string LoremKey_148 {
            get {
                return ResourceManager.GetString("LoremKey_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nunc.
        /// </summary>
        internal static string LoremKey_149 {
            get {
                return ResourceManager.GetString("LoremKey_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assum.
        /// </summary>
        internal static string LoremKey_15 {
            get {
                return ResourceManager.GetString("LoremKey_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odio.
        /// </summary>
        internal static string LoremKey_150 {
            get {
                return ResourceManager.GetString("LoremKey_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        internal static string LoremKey_151 {
            get {
                return ResourceManager.GetString("LoremKey_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orci.
        /// </summary>
        internal static string LoremKey_152 {
            get {
                return ResourceManager.GetString("LoremKey_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ornare.
        /// </summary>
        internal static string LoremKey_153 {
            get {
                return ResourceManager.GetString("LoremKey_153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parturient.
        /// </summary>
        internal static string LoremKey_154 {
            get {
                return ResourceManager.GetString("LoremKey_154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pede.
        /// </summary>
        internal static string LoremKey_155 {
            get {
                return ResourceManager.GetString("LoremKey_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pellentesque.
        /// </summary>
        internal static string LoremKey_156 {
            get {
                return ResourceManager.GetString("LoremKey_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to penatibus.
        /// </summary>
        internal static string LoremKey_157 {
            get {
                return ResourceManager.GetString("LoremKey_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phasellus.
        /// </summary>
        internal static string LoremKey_158 {
            get {
                return ResourceManager.GetString("LoremKey_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placerat.
        /// </summary>
        internal static string LoremKey_159 {
            get {
                return ResourceManager.GetString("LoremKey_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string LoremKey_16 {
            get {
                return ResourceManager.GetString("LoremKey_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platea.
        /// </summary>
        internal static string LoremKey_160 {
            get {
                return ResourceManager.GetString("LoremKey_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to porta.
        /// </summary>
        internal static string LoremKey_161 {
            get {
                return ResourceManager.GetString("LoremKey_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to porttitor.
        /// </summary>
        internal static string LoremKey_162 {
            get {
                return ResourceManager.GetString("LoremKey_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to possim.
        /// </summary>
        internal static string LoremKey_163 {
            get {
                return ResourceManager.GetString("LoremKey_163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posuere.
        /// </summary>
        internal static string LoremKey_164 {
            get {
                return ResourceManager.GetString("LoremKey_164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to praesent.
        /// </summary>
        internal static string LoremKey_165 {
            get {
                return ResourceManager.GetString("LoremKey_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pretium.
        /// </summary>
        internal static string LoremKey_166 {
            get {
                return ResourceManager.GetString("LoremKey_166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primis.
        /// </summary>
        internal static string LoremKey_167 {
            get {
                return ResourceManager.GetString("LoremKey_167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proin.
        /// </summary>
        internal static string LoremKey_168 {
            get {
                return ResourceManager.GetString("LoremKey_168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pulvinar.
        /// </summary>
        internal static string LoremKey_169 {
            get {
                return ResourceManager.GetString("LoremKey_169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auctor.
        /// </summary>
        internal static string LoremKey_17 {
            get {
                return ResourceManager.GetString("LoremKey_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purus.
        /// </summary>
        internal static string LoremKey_170 {
            get {
                return ResourceManager.GetString("LoremKey_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quam.
        /// </summary>
        internal static string LoremKey_171 {
            get {
                return ResourceManager.GetString("LoremKey_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qui.
        /// </summary>
        internal static string LoremKey_172 {
            get {
                return ResourceManager.GetString("LoremKey_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quis.
        /// </summary>
        internal static string LoremKey_173 {
            get {
                return ResourceManager.GetString("LoremKey_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quisque.
        /// </summary>
        internal static string LoremKey_174 {
            get {
                return ResourceManager.GetString("LoremKey_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quod.
        /// </summary>
        internal static string LoremKey_175 {
            get {
                return ResourceManager.GetString("LoremKey_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rebum.
        /// </summary>
        internal static string LoremKey_176 {
            get {
                return ResourceManager.GetString("LoremKey_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rhoncus.
        /// </summary>
        internal static string LoremKey_177 {
            get {
                return ResourceManager.GetString("LoremKey_177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ridiculus.
        /// </summary>
        internal static string LoremKey_178 {
            get {
                return ResourceManager.GetString("LoremKey_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to risus.
        /// </summary>
        internal static string LoremKey_179 {
            get {
                return ResourceManager.GetString("LoremKey_179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to augue.
        /// </summary>
        internal static string LoremKey_18 {
            get {
                return ResourceManager.GetString("LoremKey_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rutrum.
        /// </summary>
        internal static string LoremKey_180 {
            get {
                return ResourceManager.GetString("LoremKey_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sadipscing.
        /// </summary>
        internal static string LoremKey_181 {
            get {
                return ResourceManager.GetString("LoremKey_181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sagittis.
        /// </summary>
        internal static string LoremKey_182 {
            get {
                return ResourceManager.GetString("LoremKey_182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sanctus.
        /// </summary>
        internal static string LoremKey_183 {
            get {
                return ResourceManager.GetString("LoremKey_183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sapien.
        /// </summary>
        internal static string LoremKey_184 {
            get {
                return ResourceManager.GetString("LoremKey_184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scelerisque.
        /// </summary>
        internal static string LoremKey_185 {
            get {
                return ResourceManager.GetString("LoremKey_185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sea.
        /// </summary>
        internal static string LoremKey_186 {
            get {
                return ResourceManager.GetString("LoremKey_186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sed.
        /// </summary>
        internal static string LoremKey_187 {
            get {
                return ResourceManager.GetString("LoremKey_187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sem.
        /// </summary>
        internal static string LoremKey_188 {
            get {
                return ResourceManager.GetString("LoremKey_188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semper.
        /// </summary>
        internal static string LoremKey_189 {
            get {
                return ResourceManager.GetString("LoremKey_189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autem.
        /// </summary>
        internal static string LoremKey_19 {
            get {
                return ResourceManager.GetString("LoremKey_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to senectus.
        /// </summary>
        internal static string LoremKey_190 {
            get {
                return ResourceManager.GetString("LoremKey_190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sit.
        /// </summary>
        internal static string LoremKey_191 {
            get {
                return ResourceManager.GetString("LoremKey_191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sociis.
        /// </summary>
        internal static string LoremKey_192 {
            get {
                return ResourceManager.GetString("LoremKey_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sodales.
        /// </summary>
        internal static string LoremKey_193 {
            get {
                return ResourceManager.GetString("LoremKey_193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sollicitudin.
        /// </summary>
        internal static string LoremKey_194 {
            get {
                return ResourceManager.GetString("LoremKey_194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soluta.
        /// </summary>
        internal static string LoremKey_195 {
            get {
                return ResourceManager.GetString("LoremKey_195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stet.
        /// </summary>
        internal static string LoremKey_196 {
            get {
                return ResourceManager.GetString("LoremKey_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suscipit.
        /// </summary>
        internal static string LoremKey_197 {
            get {
                return ResourceManager.GetString("LoremKey_197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suspendisse.
        /// </summary>
        internal static string LoremKey_198 {
            get {
                return ResourceManager.GetString("LoremKey_198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takimata.
        /// </summary>
        internal static string LoremKey_199 {
            get {
                return ResourceManager.GetString("LoremKey_199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ac.
        /// </summary>
        internal static string LoremKey_2 {
            get {
                return ResourceManager.GetString("LoremKey_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bibendum.
        /// </summary>
        internal static string LoremKey_20 {
            get {
                return ResourceManager.GetString("LoremKey_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tation.
        /// </summary>
        internal static string LoremKey_200 {
            get {
                return ResourceManager.GetString("LoremKey_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te.
        /// </summary>
        internal static string LoremKey_201 {
            get {
                return ResourceManager.GetString("LoremKey_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tellus.
        /// </summary>
        internal static string LoremKey_202 {
            get {
                return ResourceManager.GetString("LoremKey_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tempor.
        /// </summary>
        internal static string LoremKey_203 {
            get {
                return ResourceManager.GetString("LoremKey_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tempus.
        /// </summary>
        internal static string LoremKey_204 {
            get {
                return ResourceManager.GetString("LoremKey_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tincidunt.
        /// </summary>
        internal static string LoremKey_205 {
            get {
                return ResourceManager.GetString("LoremKey_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tortor.
        /// </summary>
        internal static string LoremKey_206 {
            get {
                return ResourceManager.GetString("LoremKey_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tristique.
        /// </summary>
        internal static string LoremKey_207 {
            get {
                return ResourceManager.GetString("LoremKey_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turpis.
        /// </summary>
        internal static string LoremKey_208 {
            get {
                return ResourceManager.GetString("LoremKey_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ullamcorper.
        /// </summary>
        internal static string LoremKey_209 {
            get {
                return ResourceManager.GetString("LoremKey_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blandit.
        /// </summary>
        internal static string LoremKey_21 {
            get {
                return ResourceManager.GetString("LoremKey_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ultrices.
        /// </summary>
        internal static string LoremKey_210 {
            get {
                return ResourceManager.GetString("LoremKey_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ultricies.
        /// </summary>
        internal static string LoremKey_211 {
            get {
                return ResourceManager.GetString("LoremKey_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urna.
        /// </summary>
        internal static string LoremKey_212 {
            get {
                return ResourceManager.GetString("LoremKey_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ut.
        /// </summary>
        internal static string LoremKey_213 {
            get {
                return ResourceManager.GetString("LoremKey_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varius.
        /// </summary>
        internal static string LoremKey_214 {
            get {
                return ResourceManager.GetString("LoremKey_214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicula.
        /// </summary>
        internal static string LoremKey_215 {
            get {
                return ResourceManager.GetString("LoremKey_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vel.
        /// </summary>
        internal static string LoremKey_216 {
            get {
                return ResourceManager.GetString("LoremKey_216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to velit.
        /// </summary>
        internal static string LoremKey_217 {
            get {
                return ResourceManager.GetString("LoremKey_217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to venenatis.
        /// </summary>
        internal static string LoremKey_218 {
            get {
                return ResourceManager.GetString("LoremKey_218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to veniam.
        /// </summary>
        internal static string LoremKey_219 {
            get {
                return ResourceManager.GetString("LoremKey_219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clita.
        /// </summary>
        internal static string LoremKey_22 {
            get {
                return ResourceManager.GetString("LoremKey_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vero.
        /// </summary>
        internal static string LoremKey_220 {
            get {
                return ResourceManager.GetString("LoremKey_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vestibulum.
        /// </summary>
        internal static string LoremKey_221 {
            get {
                return ResourceManager.GetString("LoremKey_221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vitae.
        /// </summary>
        internal static string LoremKey_222 {
            get {
                return ResourceManager.GetString("LoremKey_222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vivamus.
        /// </summary>
        internal static string LoremKey_223 {
            get {
                return ResourceManager.GetString("LoremKey_223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viverra.
        /// </summary>
        internal static string LoremKey_224 {
            get {
                return ResourceManager.GetString("LoremKey_224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voluptua.
        /// </summary>
        internal static string LoremKey_225 {
            get {
                return ResourceManager.GetString("LoremKey_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volutpat.
        /// </summary>
        internal static string LoremKey_226 {
            get {
                return ResourceManager.GetString("LoremKey_226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vulputate.
        /// </summary>
        internal static string LoremKey_227 {
            get {
                return ResourceManager.GetString("LoremKey_227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wisi.
        /// </summary>
        internal static string LoremKey_228 {
            get {
                return ResourceManager.GetString("LoremKey_228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzril.
        /// </summary>
        internal static string LoremKey_229 {
            get {
                return ResourceManager.GetString("LoremKey_229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commodo.
        /// </summary>
        internal static string LoremKey_23 {
            get {
                return ResourceManager.GetString("LoremKey_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condimentum.
        /// </summary>
        internal static string LoremKey_24 {
            get {
                return ResourceManager.GetString("LoremKey_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to congue.
        /// </summary>
        internal static string LoremKey_25 {
            get {
                return ResourceManager.GetString("LoremKey_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consectetuer.
        /// </summary>
        internal static string LoremKey_26 {
            get {
                return ResourceManager.GetString("LoremKey_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consequat.
        /// </summary>
        internal static string LoremKey_27 {
            get {
                return ResourceManager.GetString("LoremKey_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consetetur.
        /// </summary>
        internal static string LoremKey_28 {
            get {
                return ResourceManager.GetString("LoremKey_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cras.
        /// </summary>
        internal static string LoremKey_29 {
            get {
                return ResourceManager.GetString("LoremKey_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accumsan.
        /// </summary>
        internal static string LoremKey_3 {
            get {
                return ResourceManager.GetString("LoremKey_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubilia.
        /// </summary>
        internal static string LoremKey_30 {
            get {
                return ResourceManager.GetString("LoremKey_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cum.
        /// </summary>
        internal static string LoremKey_31 {
            get {
                return ResourceManager.GetString("LoremKey_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curabitur.
        /// </summary>
        internal static string LoremKey_32 {
            get {
                return ResourceManager.GetString("LoremKey_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curae.
        /// </summary>
        internal static string LoremKey_33 {
            get {
                return ResourceManager.GetString("LoremKey_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cursus.
        /// </summary>
        internal static string LoremKey_34 {
            get {
                return ResourceManager.GetString("LoremKey_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dapibus.
        /// </summary>
        internal static string LoremKey_35 {
            get {
                return ResourceManager.GetString("LoremKey_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delenit.
        /// </summary>
        internal static string LoremKey_36 {
            get {
                return ResourceManager.GetString("LoremKey_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diam.
        /// </summary>
        internal static string LoremKey_37 {
            get {
                return ResourceManager.GetString("LoremKey_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dictum.
        /// </summary>
        internal static string LoremKey_38 {
            get {
                return ResourceManager.GetString("LoremKey_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dictumst.
        /// </summary>
        internal static string LoremKey_39 {
            get {
                return ResourceManager.GetString("LoremKey_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accusam.
        /// </summary>
        internal static string LoremKey_4 {
            get {
                return ResourceManager.GetString("LoremKey_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dignissim.
        /// </summary>
        internal static string LoremKey_40 {
            get {
                return ResourceManager.GetString("LoremKey_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dis.
        /// </summary>
        internal static string LoremKey_41 {
            get {
                return ResourceManager.GetString("LoremKey_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dolor.
        /// </summary>
        internal static string LoremKey_42 {
            get {
                return ResourceManager.GetString("LoremKey_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dolore.
        /// </summary>
        internal static string LoremKey_43 {
            get {
                return ResourceManager.GetString("LoremKey_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dolores.
        /// </summary>
        internal static string LoremKey_44 {
            get {
                return ResourceManager.GetString("LoremKey_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doming.
        /// </summary>
        internal static string LoremKey_45 {
            get {
                return ResourceManager.GetString("LoremKey_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donec.
        /// </summary>
        internal static string LoremKey_46 {
            get {
                return ResourceManager.GetString("LoremKey_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dui.
        /// </summary>
        internal static string LoremKey_47 {
            get {
                return ResourceManager.GetString("LoremKey_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duis.
        /// </summary>
        internal static string LoremKey_48 {
            get {
                return ResourceManager.GetString("LoremKey_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duo.
        /// </summary>
        internal static string LoremKey_49 {
            get {
                return ResourceManager.GetString("LoremKey_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ad.
        /// </summary>
        internal static string LoremKey_5 {
            get {
                return ResourceManager.GetString("LoremKey_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ea.
        /// </summary>
        internal static string LoremKey_50 {
            get {
                return ResourceManager.GetString("LoremKey_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to egestas.
        /// </summary>
        internal static string LoremKey_51 {
            get {
                return ResourceManager.GetString("LoremKey_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eget.
        /// </summary>
        internal static string LoremKey_52 {
            get {
                return ResourceManager.GetString("LoremKey_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eirmod.
        /// </summary>
        internal static string LoremKey_53 {
            get {
                return ResourceManager.GetString("LoremKey_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleifend.
        /// </summary>
        internal static string LoremKey_54 {
            get {
                return ResourceManager.GetString("LoremKey_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elementum.
        /// </summary>
        internal static string LoremKey_55 {
            get {
                return ResourceManager.GetString("LoremKey_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elit.
        /// </summary>
        internal static string LoremKey_56 {
            get {
                return ResourceManager.GetString("LoremKey_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elitr.
        /// </summary>
        internal static string LoremKey_57 {
            get {
                return ResourceManager.GetString("LoremKey_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enim.
        /// </summary>
        internal static string LoremKey_58 {
            get {
                return ResourceManager.GetString("LoremKey_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eos.
        /// </summary>
        internal static string LoremKey_59 {
            get {
                return ResourceManager.GetString("LoremKey_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adipiscing.
        /// </summary>
        internal static string LoremKey_6 {
            get {
                return ResourceManager.GetString("LoremKey_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erat.
        /// </summary>
        internal static string LoremKey_60 {
            get {
                return ResourceManager.GetString("LoremKey_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eros.
        /// </summary>
        internal static string LoremKey_61 {
            get {
                return ResourceManager.GetString("LoremKey_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esse.
        /// </summary>
        internal static string LoremKey_62 {
            get {
                return ResourceManager.GetString("LoremKey_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est.
        /// </summary>
        internal static string LoremKey_63 {
            get {
                return ResourceManager.GetString("LoremKey_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        internal static string LoremKey_64 {
            get {
                return ResourceManager.GetString("LoremKey_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etiam.
        /// </summary>
        internal static string LoremKey_65 {
            get {
                return ResourceManager.GetString("LoremKey_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eu.
        /// </summary>
        internal static string LoremKey_66 {
            get {
                return ResourceManager.GetString("LoremKey_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to euismod.
        /// </summary>
        internal static string LoremKey_67 {
            get {
                return ResourceManager.GetString("LoremKey_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eum.
        /// </summary>
        internal static string LoremKey_68 {
            get {
                return ResourceManager.GetString("LoremKey_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex.
        /// </summary>
        internal static string LoremKey_69 {
            get {
                return ResourceManager.GetString("LoremKey_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aenean.
        /// </summary>
        internal static string LoremKey_7 {
            get {
                return ResourceManager.GetString("LoremKey_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exerci.
        /// </summary>
        internal static string LoremKey_70 {
            get {
                return ResourceManager.GetString("LoremKey_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facer.
        /// </summary>
        internal static string LoremKey_71 {
            get {
                return ResourceManager.GetString("LoremKey_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facilisi.
        /// </summary>
        internal static string LoremKey_72 {
            get {
                return ResourceManager.GetString("LoremKey_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facilisis.
        /// </summary>
        internal static string LoremKey_73 {
            get {
                return ResourceManager.GetString("LoremKey_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fames.
        /// </summary>
        internal static string LoremKey_74 {
            get {
                return ResourceManager.GetString("LoremKey_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faucibus.
        /// </summary>
        internal static string LoremKey_75 {
            get {
                return ResourceManager.GetString("LoremKey_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to felis.
        /// </summary>
        internal static string LoremKey_76 {
            get {
                return ResourceManager.GetString("LoremKey_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fermentum.
        /// </summary>
        internal static string LoremKey_77 {
            get {
                return ResourceManager.GetString("LoremKey_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feugait.
        /// </summary>
        internal static string LoremKey_78 {
            get {
                return ResourceManager.GetString("LoremKey_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feugiat.
        /// </summary>
        internal static string LoremKey_79 {
            get {
                return ResourceManager.GetString("LoremKey_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aliquam.
        /// </summary>
        internal static string LoremKey_8 {
            get {
                return ResourceManager.GetString("LoremKey_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fringilla.
        /// </summary>
        internal static string LoremKey_80 {
            get {
                return ResourceManager.GetString("LoremKey_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fusce.
        /// </summary>
        internal static string LoremKey_81 {
            get {
                return ResourceManager.GetString("LoremKey_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gravida.
        /// </summary>
        internal static string LoremKey_82 {
            get {
                return ResourceManager.GetString("LoremKey_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gubergren.
        /// </summary>
        internal static string LoremKey_83 {
            get {
                return ResourceManager.GetString("LoremKey_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to habitant.
        /// </summary>
        internal static string LoremKey_84 {
            get {
                return ResourceManager.GetString("LoremKey_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to habitasse.
        /// </summary>
        internal static string LoremKey_85 {
            get {
                return ResourceManager.GetString("LoremKey_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hac.
        /// </summary>
        internal static string LoremKey_86 {
            get {
                return ResourceManager.GetString("LoremKey_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hendrerit.
        /// </summary>
        internal static string LoremKey_87 {
            get {
                return ResourceManager.GetString("LoremKey_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iaculis.
        /// </summary>
        internal static string LoremKey_88 {
            get {
                return ResourceManager.GetString("LoremKey_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string LoremKey_89 {
            get {
                return ResourceManager.GetString("LoremKey_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aliquet.
        /// </summary>
        internal static string LoremKey_9 {
            get {
                return ResourceManager.GetString("LoremKey_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illum.
        /// </summary>
        internal static string LoremKey_90 {
            get {
                return ResourceManager.GetString("LoremKey_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imperdiet.
        /// </summary>
        internal static string LoremKey_91 {
            get {
                return ResourceManager.GetString("LoremKey_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string LoremKey_92 {
            get {
                return ResourceManager.GetString("LoremKey_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integer.
        /// </summary>
        internal static string LoremKey_93 {
            get {
                return ResourceManager.GetString("LoremKey_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interdum.
        /// </summary>
        internal static string LoremKey_94 {
            get {
                return ResourceManager.GetString("LoremKey_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invidunt.
        /// </summary>
        internal static string LoremKey_95 {
            get {
                return ResourceManager.GetString("LoremKey_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipsum.
        /// </summary>
        internal static string LoremKey_96 {
            get {
                return ResourceManager.GetString("LoremKey_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iriure.
        /// </summary>
        internal static string LoremKey_97 {
            get {
                return ResourceManager.GetString("LoremKey_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iusto.
        /// </summary>
        internal static string LoremKey_98 {
            get {
                return ResourceManager.GetString("LoremKey_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to justo.
        /// </summary>
        internal static string LoremKey_99 {
            get {
                return ResourceManager.GetString("LoremKey_99", resourceCulture);
            }
        }
    }
}
